### ISSUE TITLE
Fatal Javascript error

### ISSUE THREAD

**Issue by OscarVsp** [Zwylair/BetterDiscordAutoInstaller#1]
Hello,

After installing this (using the exact commands on the README), the installation itself went well but I got a fatal javascript error when discord try to start.

![image](https://github.com/Zwylair/BetterDiscordAutoInstaller/assets/30955488/d6840e92-4dda-4f14-a47c-aebd6ef6ab08)

Any idea how to fix ?

Also, maybe add a way to remove the installation ?

**Comment by Zwylair** [comment]
Hi

This may be due to the script not being able to download betterdiscord.asar from the official repository. This could be a problem with your internet connection or specific settings of your antivirus/firewall. Try the conditions to make sure that this cannot be the cause of the problem.
