### ISSUE TITLE
Not pulling files from correct folder

### ISSUE THREAD

**Issue by FayeShiro** [Zwylair/BetterDiscordAutoInstaller#2]
When attempting to install dependencies / run installer the script attempts to pull directly from the (Username) folder, and not the BetterDiscordAutoInstaller folder contained within, causing it to fail. Copying contents outside of this folder allows it to continue of course

**Comment by Zwylair** [comment]
Hi

The problem may be that in your shortcut in the "Working folder" field there is a folder with the user. Change this value to the folder with the script, and if it doesn't help, let me know
