### ISSUE TITLE
Doesn't check version before running

### ISSUE THREAD

**Issue by sauronshotdogs** [Zwylair/BetterDiscordAutoInstaller#21]
It will always run on startup, regardless of whether new version or not.

I just installed it through the exe, but it seems to not update the settings.json, unless um doing something wrong?

**Comment by Zwylair** [comment]
yes, the settings.json file is indeed not updated after startup, although it should be. i'll fix it now

**Comment by sauronshotdogs** [comment]
Thanks a bunch!

**Comment by Zwylair** [comment]
fixed

**Comment by sauronshotdogs** [comment]
mind recompiling the exe with the changes?

**Comment by Zwylair** [comment]
i did. i just updated the 1.2.5 zip instead of publishing a new release
