### ISSUE TITLE
Hangs on Updating discord to latest version...

### ISSUE THREAD

**Issue by jacobrreed** [Zwylair/BetterDiscordAutoInstaller#3]
![image](https://github.com/Zwylair/BetterDiscordAutoInstaller/assets/25580051/0d1bc59f-f2fd-4e7a-b95c-23cab421d3b3)

Doesn't get past this

**Comment by jacobrreed** [comment]
I just commented out the lines where it updates discord and it works

**Comment by Zwylair** [comment]
Discord starts `gpu_encoder_helper.exe` when it updated and ready to run, so my script is just waiting for it. Try reducing the time it waits for `gpu_encoder_helper.exe` in line 52: `time.sleep(0.5)` => `time.sleep(0.1)` and let me know if that helped.

**Comment by Zwylair** [comment]
Fixed with v1.1.0 update
