### ISSUE TITLE
Suggestion: Handle on discord update

### ISSUE THREAD

**Issue by KairuByte** [Zwylair/BetterDiscordAutoInstaller#4]
I'm wondering if there is a sane way to kick off the patcher when a discord update is detected, instead of when the system starts? Sometimes discord crashes, or you kill it, or you hit the update button, which then kicks off an update.

**Comment by KairuByte** [comment]
Another reason is that the current method doesn't seem that reliable. I'm getting a similar issue to #3 even after removing the 0.1 second wait time in the loop (yeah terrible I know.) It seems that process isn't always kicked off, or it's being started and stopped so fast that it's completely impossible for it to be detected.

**Comment by Zwylair** [comment]
Well, I need to spend more time researching the discord update process so that the script can hook something more reliable than `gpu_encoder_helper.exe`. If I find something suitable, I'll post an update soon.

**Comment by Zwylair** [comment]
I have updated the method of tracking discord updates, try the script now.

**Comment by KairuByte** [comment]
Initially it would not run, but just now when trying to grab the error it did work.... Mostly. It failed the first time, because discord failed to update and retried. The retry was after the patching had been completed, so I had to run it again. Did work that last time though.

**Comment by Zwylair** [comment]
I made the update a more robust process by adding a couple of checks using a different discord startup argument. Now I have checked everything on different computers, I also checked how it updates the discord and then patches it. I hope this will be the last fix and there will only be new features from now on 😅

**Comment by KairuByte** [comment]
Does seem to be working flawlessly now. ^_^
