### ISSUE TITLE
Problem with startupmanager (got_imput)

### ISSUE THREAD

**Issue by overnite22** [Zwylair/BetterDiscordAutoInstaller#7]
File ".\startup_manager.py", line 39
    match got_input:
          ^
SyntaxError: invalid syntax

**Comment by Zwylair** [comment]
The BetterDiscordAutoInstaller is meant to run on python 3.11. `startup_manager.py` script uses the match case construction that was added in python 3.10, and if you get a SyntaxError, it means you are using a python version before 3.10

**Comment by overnite22** [comment]
yeah just noticed i did not update to 3.12 on my main machine lol
ty friend ^^
